Repository BedrockStreaming/tech.bedrockstreaming.com, pull requests merged in 2021-11, with the labels that each got.

#281 Retour du Forum PHP 2021
  _posts/2021-11-02-forum-php-2021.md
  images/posts/forumphp2021/bedrock_team.jpg
  images/posts/forumphp2021/benoit_speaker.jpg
  images/posts/forumphp2021/header.jpg
  images/posts/forumphp2021/sofia_speaker.jpg
Labels: Ready for Review

#277 feat(post): egress controller
  _posts/2021-10-18-increase-performance-and-stability-by-adding-an-egress-controller.md
  images/posts/2021-10-18-increase-performance-and-stability-by-adding-an-egress-controller/cpu-metrics.png
  images/posts/2021-10-18-increase-performance-and-stability-by-adding-an-egress-controller/detailed-configuration.png
  images/posts/2021-10-18-increase-performance-and-stability-by-adding-an-egress-controller/error-port-allocation.png
  images/posts/2021-10-18-increase-performance-and-stability-by-adding-an-egress-controller/outgoing-traffic-with-egress-schema.png
  images/posts/2021-10-18-increase-performance-and-stability-by-adding-an-egress-controller/outgoing-traffic-without-egress-schema.png
Labels: Ready for Review, ok to merge

#282 Ajout des liens vers les vidéos du ForumPHP 2021
  _posts/2021-11-02-forum-php-2021.md
Labels: Ready for Review

#285 feat(post): load balancing and caching at aws
  _posts/2021-11-18-hsdo.md
  images/posts/2021-11-18-hsdo/hsdo.png
  images/posts/2021-11-18-hsdo/image1.png
  images/posts/2021-11-18-hsdo/image10.png
  images/posts/2021-11-18-hsdo/image11.png
  images/posts/2021-11-18-hsdo/image2.png
  images/posts/2021-11-18-hsdo/image3.png
  images/posts/2021-11-18-hsdo/image4.png
  images/posts/2021-11-18-hsdo/image5.png
  images/posts/2021-11-18-hsdo/image6.png
  images/posts/2021-11-18-hsdo/image7.png
  images/posts/2021-11-18-hsdo/image8.png
  images/posts/2021-11-18-hsdo/image9.png
Labels: work in progress
