Repository BedrockStreaming/tech.bedrockstreaming.com, pull requests merged in 2022-07, with the labels that each got.

#344 feat(layout): create a layout for conferences
  CONTRIBUTING.md
  _data/authors.yml
  _data/conferences.yaml
  _layouts/conference-list.liquid
  _layouts/conference.liquid
  _layouts/video-list.liquid
  _posts/2015-06-04-m6web-au-phptour-luxembourg.md
  _posts/2016-05-24-arretons-de-perdre-du-temps.md
  _posts/2016-05-25-m6web-retourdxp-cassandra.md
  _posts/2016-11-24-une-donnee-presque-parfaite.md
  _posts/2018-10-26-docker-en-prod-oui-avec-kubernetes-pascal-martin.md
  _posts/2018-10-26-generators-for-async-programming-user-manual.md
  _posts/2019-01-14-7-conseils-pour-demarrer-avec-spark.md
  _posts/2019-10-25-one-year-of-asynchronous-code-in-production.md
  _posts/2019-10-25-une-application-resiliente-dans-un-monde-partiellement-degrade-pascal-martin.md
  _posts/2020-02-07-pascal-martin-laduckconf.md
  _posts/2020-02-10-apache-spark-et-le-machine-learning-reves-et-realites.md
  _posts/2020-06-24-6play_API-v2-Final(1).md
  _posts/2020-06-24-devops-je-n-ai-jamais-voulu-faire.md
  _posts/2020-10-23-l'open-source-ce-n-est-pas-que-pour-le-web.md
  _posts/2020-11-23-php-cest-vous-et-vous-pouvez-contribuer-pascal-martin.md
  _posts/2021-01-21-machine-learning-en-production.md
  _posts/2021-03-11-migration-6play-vers-le-cloud-retour-experience-pascal-martin.md
  _posts/2021-03-30-comment-nous-reduisons-augmentation-couts-aws-pascal-martin.md
  _posts/2021-05-25-productionizing-ml-systems-without-fear-nor-heroism.md
  _posts/2021-06-11-no-code-developpement-applications-ouvert-autres-metiers-pascal-martin.md
  _posts/2021-10-21-confiance-aux-devs-de-votre-team.md
  _posts/2021-10-21-fiber-the-open-door-to-async.md
  _posts/2022-04-04-comment-faire-un-trailer-qui-dechire-avec-des-technos-web.md
  _posts/2022-04-21-vite-the-webpack-killer.md
  _posts/2022-05-13-docker-meetup-you-build-it-you-run-it.md
  _posts/2022-06-08-comment-ne-pas-jeter-votre-application.md
  _posts/2022-06-08-migration-progressive-vers-redux-toolkit.md
  pages/meetup-conference.md
Labels: Size/L

#348 GHA workflow to deploy, to use same workflow than dev one
  .github/workflows/integration.yml
Labels: Size/XS

#349 feat(gha): separate CI and CD workflows
  .github/workflows/deployment.yml
  .github/workflows/integration.yml
Labels: Size/XS

#352 DevFacts #17
  _posts/2022-07-22-bedrock-dev-facts-17.md
  images/posts/dev-facts-17/die-to-test.png
  images/posts/dev-facts-17/mob-programming.png
  images/posts/dev-facts-17/type-30-keyboard.png
Labels: Size/M

#353 docs(readme): udpate badges
  README.md
Labels: Size/XS
