Repository BedrockStreaming/tech.bedrockstreaming.com, pull requests merged in 2022-09, with the labels that each got.

#368 feat: add article about Kubernetes prescaling opensourcing
  _data/authors.yml
  _posts/2022-09-01-kubernetes-prescaling-we-open-source-our-solution.md
  images/posts/2022-09-01-kubernetes-prescaling-we-open-source-our-solution/br-opensource.png
  images/posts/2022-09-01-kubernetes-prescaling-we-open-source-our-solution/post-prescaling-event.png
  images/posts/br-logo.png
  pages/oss.md
Labels: Size/M

#377 fix: non-interpreted link
  _posts/2022-09-01-kubernetes-prescaling-we-open-source-our-solution.md
Labels: Size/XS

#365 Feat/bff circuit breaker 4
  _posts/2022-06-10-backend-bff-intro.md
  _posts/2022-08-12-backend-fallbacks.md
  _posts/2022-08-25-backend-errors-connections.md
  _posts/2022-09-02-backend-circuit-breaker.md
  images/posts/2022-09-02-backend-circuit-breaker/monitoring-1.png
  images/posts/2022-09-02-backend-circuit-breaker/monitoring-2.png
  images/posts/2022-09-02-backend-circuit-breaker/progress-bar.png
Labels: Ready for Review, Size/M

#373 Feat: add article ml
  _posts/2022-09-05-machine-learning-if-else.md
  images/posts/2022-09-05-machine-learning-if-else/ML recap.png
  images/posts/2022-09-05-machine-learning-if-else/decision_tree.png
  images/posts/2022-09-05-machine-learning-if-else/decision_tree_final.png
  images/posts/2022-09-05-machine-learning-if-else/decision_tree_first_step.png
  images/posts/2022-09-05-machine-learning-if-else/decision_tree_second_step.png
  images/posts/2022-09-05-machine-learning-if-else/formula.png
  images/posts/2022-09-05-machine-learning-if-else/unicorn_forest.jpg
Labels: Size/M

#379 Feat/article/monitoring at scale with victoriametrics
  _data/authors.yml
  _posts/2022-09-06-monitoring-at-scale-with-victoriametrics.md
  images/avatar/jmenan.jpg
  images/posts/2022-09-06-monitoring-at-scale-with-victoriametrics/active-ts-poc-vm.png
  images/posts/2022-09-06-monitoring-at-scale-with-victoriametrics/active-ts-vm-last-6m.png
  images/posts/2022-09-06-monitoring-at-scale-with-victoriametrics/cardinality-example.png
  images/posts/2022-09-06-monitoring-at-scale-with-victoriametrics/churn-rate-vm-last-6m.png
  images/posts/2022-09-06-monitoring-at-scale-with-victoriametrics/cpu-poc-vm.png
  images/posts/2022-09-06-monitoring-at-scale-with-victoriametrics/cpu-usage-vm-last-6m.png
  images/posts/2022-09-06-monitoring-at-scale-with-victoriametrics/ingestion-rate-vm-last-6m.png
  images/posts/2022-09-06-monitoring-at-scale-with-victoriametrics/logo-vm.png
  images/posts/2022-09-06-monitoring-at-scale-with-victoriametrics/prometheus-cpu.png
  images/posts/2022-09-06-monitoring-at-scale-with-victoriametrics/prometheus-ram.png
  images/posts/2022-09-06-monitoring-at-scale-with-victoriametrics/ram-usage-vm-last-6m.png
  images/posts/2022-09-06-monitoring-at-scale-with-victoriametrics/sample-rate-vm-last-6m.png
  images/posts/2022-09-06-monitoring-at-scale-with-victoriametrics/scrape-target-vm-last-6m.png
  images/posts/2022-09-06-monitoring-at-scale-with-victoriametrics/stack-vm.png
  images/posts/2022-09-06-monitoring-at-scale-with-victoriametrics/total-datapoint-vm-last-6m.png
Labels: Size/M

#378 Update oss.md
  pages/oss.md
Labels: Size/XS

#380 fix: syntax and duplicate entrie
  _posts/2022-09-06-monitoring-at-scale-with-victoriametrics.md
Labels: Size/XS

#382 Update 2022-09-02-backend-circuit-breaker.md
  _posts/2022-09-02-backend-circuit-breaker.md
Labels: Size/XS

#381 feat: add subtitling/captioning article
  _data/authors.yml
  _posts/2022-09-20-captioning-in-the-streaming-world.md
  images/avatar/hugo.jpg
Labels: Size/S
