Repository BedrockStreaming/tech.bedrockstreaming.com, pull requests merged in 2022-08, with the labels that each got.

#354 JSCodeshift blog post
  _data/authors.yml
  _posts/2022-07-26-refactorer-avec-jscodeshift.md
  images/avatar/m_schneider.png
  images/posts/refactorer-avec-jscodeshift/102-implementation.png
  images/posts/refactorer-avec-jscodeshift/astexplorer.png
Labels: Ready for Review, Size/M

#357 New Post MiXiT 2022
  _data/authors.yml
  _posts/2022-07-28-retour-sur-mixit-2022.md
  images/posts/mixit-crepes.jpg
Labels: Size/M

#358 feat(BlogPost): add post about private Cdn logs
  _data/authors.yml
  _posts/2022-08-08-private-cdn-logs.md
  images/avatar/arthurzinck.png
  images/posts/2022-08-08-privateCdnLogs/image1.png
  images/posts/2022-08-08-privateCdnLogs/image2.png
  images/posts/2022-08-08-privateCdnLogs/image3.png
  images/posts/2022-08-08-privateCdnLogs/image4.png
  images/posts/2022-08-08-privateCdnLogs/image5.png
  images/posts/2022-08-08-privateCdnLogs/main.png
Labels: Ready for Review, Size/M

#361 feat: change heading style for reading purpose
  _sass/base/_global.scss
  _sass/base/_variables.scss
Labels: Ready for Review, Size/XS

#359 feat: add a second article about the backend architecture
  _posts/2022-06-10-backend-bff-intro.md
  _posts/2022-08-12-backend-fallbacks.md
  images/posts/2022-08-12-backend-fallbacks/ddd-page-full.png
  images/posts/2022-08-12-backend-fallbacks/ddd-page-min.png
  images/posts/2022-08-12-backend-fallbacks/stale-cache-usage.png
Labels: Ready for Review, Size/M

#367 fix: update usage of stale cache headers with more information
  _posts/2022-08-12-backend-fallbacks.md
Labels: bug, Ready for Review, Size/XS

#360 feat: add june 2022 LFT videos
  _data/authors.yml
  _posts/2022-06-03-amateur-de-pression.md
  _posts/2022-06-03-comment-faire-un-trailer-video-qui-dechire-avec-les-technos-web.md
  _posts/2022-06-03-connaissez-vous-cache°cache.md
  _posts/2022-06-03-creer-un-jeu-video-en-moins-dune-heure-sur-unity.md
  _posts/2022-06-03-errances-a-kiilopaala.md
  _posts/2022-06-03-la-pression-je-ne-la-subis-pas-je-la-fais.md
  _posts/2022-06-03-🍪-its-cookie-jar-time-🍪.md
Labels: Ready for Review, Size/M

#369 fix: use correct name for hugo
  _data/authors.yml
  _posts/2022-06-03-amateur-de-pression.md
Labels: Size/XS

#371 fix: use Mathieu with one 't'
  _data/authors.yml
  _posts/2022-06-03-la-pression-je-ne-la-subis-pas-je-la-fais.md
Labels: Size/XS

#364 feat: add a third article about the backend architecture
  _posts/2022-04-20-aws-summit-2022-notre-retour-dexperience.md
  _posts/2022-06-10-backend-bff-intro.md
  _posts/2022-08-12-backend-fallbacks.md
  _posts/2022-08-25-backend-errors-connections.md
Labels: Ready for Review, Size/M

#372 feat(tracking): setup matomo tracking method
  _config.yml
  _includes/default/head.liquid
Labels: Ready for Review, Size/XS

#374 feat(tracking): update matomo script config
  _includes/default/head.liquid
Labels: Ready for Review, Size/XS

#370 feat: add an article about spikes
  _data/authors.yml
  _posts/2022-08-23-how-to-spike.md
  images/avatar/e_doyon.jpeg
  images/posts/how-to-spike/cactus.jpg
Labels: Ready for Review, Size/M

#375 feat(tech-blog): show more posts, add youtube link and fmt
  _config.yml
  _data/icons.yml
  _includes/default/head.liquid
Labels: Ready for Review, Size/XS

#376 feat: remove about page
  pages/about.md
Labels: Size/XS
