Repository BedrockStreaming/tech.bedrockstreaming.com, pull requests merged in 2022-06, with the labels that each got.

#319 chore(ruby): upgrade dependencies to ruby 3
  .bundle/config
  .github/workflows/integration.yml
  .tweet-cache/02b591d77a446cb7531ab71b75d3d2bc.cache
  .tweet-cache/22137a3ee021202d9b96f253bdf0b832.cache
  .tweet-cache/fda006a98be0f21d5a2d37a348d2a360.cache
  Dockerfile
  Gemfile
  Gemfile.lock
  _data/authors.yml
  images/avatar/acaron.jpeg
Labels: Size/M

#321 Feat/backend bff
  Gemfile.lock
  _data/authors.yml
  _posts/2022-06-10-backend-bff-intro.md
  images/avatar/v_claras.jpg
  images/posts/2022-06-10-backend-bff-intro/architecture-new.png
  images/posts/2022-06-10-backend-bff-intro/architecture-old.png
  images/posts/2022-06-10-backend-bff-intro/bff.png
  images/posts/2022-06-10-backend-bff-intro/presentation-explanation.png
  images/posts/2022-06-10-backend-bff-intro/presentation-new.png
  images/posts/2022-06-10-backend-bff-intro/presentation-old.png
Labels: Ready for Review, Size/M

#322 Fix/backend bff intro
  _posts/2022-06-10-backend-bff-intro.md
  images/posts/2022-06-10-backend-bff-intro/bff.png
Labels: Ready for Review, Size/XS

#324 feat: add figure and figcaption element
  Gemfile
  Gemfile.lock
  _config.yml
  _sass/layouts/_posts.scss
Labels: Size/XS

#320 feat: create LFT and meetup pages
  CONTRIBUTING.md
  _layouts/video-list.liquid
  _layouts/video.liquid
  _posts/2013-05-06-la-poo-canada-dry.md
  _posts/2013-05-22-redis-on-fire.md
  _posts/2013-06-26-encodage-packaging-drm-tout-sur-la-video.md
  _posts/2013-07-19-introduction-a-drupal-par-claire-roubey-clever-age.md
  _posts/2013-10-08-le-nosql-focus-sur-mongodb-par-cedric-derue-altran.md
  _posts/2013-10-09-distribuez-votre-video-partout-avec-3-euros-en-poche-et-devenez-millionaire-ou-presque.md
  _posts/2014-01-18-vagrant-julien-bianchi.md
  _posts/2015-04-01-immutablejs-relay-graphql-react-native.md
  _posts/2015-06-04-m6web-au-phptour-luxembourg.md
  _posts/2016-05-25-m6web-retourdxp-cassandra.md
  _posts/2016-11-24-une-donnee-presque-parfaite.md
  _posts/2020-02-07-pascal-martin-laduckconf.md
  _posts/2022-04-04-comment-faire-un-trailer-qui-dechire-avec-des-technos-web.md
  pages/lft.md
  pages/meetup-conference.md
Labels: Ready for Review, Size/M

#323 feat: first article about kubecon 2022
  _posts/2022-06-13-kubecon-2022-part-1.md
  images/posts/2022-06-13-kubecon-2022/end-part1.jpg
  images/posts/2022-06-13-kubecon-2022/main.jpg
  images/posts/2022-06-13-kubecon-2022/part1.jpg
  images/posts/2022-06-13-kubecon-2022/vpa.jpg
Labels: Ready for Review, Size/S

#331 Revert "feat: add figure and figcaption element"
  Gemfile
  Gemfile.lock
  _config.yml
  _sass/layouts/_posts.scss
Labels: Size/XS

#332 fix: remove figure element
  _posts/2022-06-13-kubecon-2022-part-1.md
Labels: Size/XS

#329 fix: use correct link for tags in post
  _includes/default/tags_list.liquid
Labels: Ready for Review, Size/XS

#330 feat: add articles about b_viguier conference
  _posts/2018-10-26-generators-for-async-programming-user-manual.md
  _posts/2019-10-25-one-year-of-asynchronous-code-in-production.md
  _posts/2020-06-24-6play_API-v2-Final(1).md
  _posts/2021-10-21-fiber-the-open-door-to-async.md
Labels: Ready for Review, Size/XS

#325 KubeCon EU 2022: part 2
  _posts/2022-06-13-kubecon-2022-part-1.md
  _posts/2022-06-14-kubecon-2022-part-2.md
  images/posts/2022-06-13-kubecon-2022/end-part2.jpg
  images/posts/2022-06-13-kubecon-2022/part2.jpg
Labels: Size/S

#327 feat: add lyon-js talk about redux toolkit
  _data/authors.yml
  _posts/2022-06-08-migration-progressive-vers-redux-toolkit.md
  images/avatar/m_blanc.jpeg
Labels: Size/XS

#335 feat: enhance display of video cards
  _layouts/video-list.liquid
Labels: Ready for Review, Size/XS

#334 feat: add talk with a_caron and friends
  _posts/2022-04-21-vite-the-webpack-killer.md
  _posts/2022-06-08-comment-ne-pas-jeter-votre-application.md
Labels: Ready for Review, Size/XS

#333 Quelques talks de P. Martin
  _posts/2018-11-14-docker-en-prod-oui-avec-kubernetes-pascal-martin.md
  _posts/2019-11-25-une-application-resiliente-dans-un-monde-partiellement-degrade-pascal-martin.md
  _posts/2020-11-18-php-cest-vous-et-vous-pouvez-contribuer-pascal-martin.md
  _posts/2021-04-02-migration-6play-vers-le-cloud-retour-experience-pascal-martin.md
  _posts/2021-04-06-comment-nous-reduisons-augmentation-couts-aws-pascal-martin.md
  _posts/2021-07-27-no-code-developpement-applications-ouvert-autres-metiers-pascal-martin.md
Labels: Size/M

#337 docs: enhance usage of video carrousel
  CONTRIBUTING.md
Labels: Size/XS

#326 KubeCon EU 2022: part 3
  _posts/2022-06-13-kubecon-2022-part-1.md
  _posts/2022-06-15-kubecon-2022-part-3.md
  images/posts/2022-06-13-kubecon-2022/end-part3.jpg
  images/posts/2022-06-13-kubecon-2022/part3-gitops-power-responsibility.png
  images/posts/2022-06-13-kubecon-2022/part3.jpg
Labels: Size/S

#339 fix: social links in footer
  _data/icons.yml
  _data/icons_builder.yml
Labels: Ready for Review, Size/XS

#328 KubeCon EU 2022: part 4
  _posts/2022-06-13-kubecon-2022-part-1.md
  _posts/2022-06-15-kubecon-2022-part-3.md
  _posts/2022-06-16-kubecon-2022-part-4.md
  images/posts/2022-06-13-kubecon-2022/end-part4.jpg
  images/posts/2022-06-13-kubecon-2022/part4.jpg
Labels: Size/S

#336 feat: add new docker meetup videos
  _data/authors.yml
  _posts/2022-05-13-docker-meetup-you-build-it-you-run-it.md
Labels: Size/XS

#342 feat: start the list of conferences
  pages/meetup-conference.md
Labels: Ready for Review, Size/XS

#340 feat: add sofia talks
  _data/authors.yml
  _posts/2020-06-24-devops-je-n-ai-jamais-voulu-faire.md
  _posts/2021-10-21-confiance-aux-devs-de-votre-team.md
  images/avatar/s_lescano.jpeg
Labels: Ready for Review, Size/XS

#345 feat: add talks for Nastasia Saby
  _posts/2016-04-24-arretons-de-perdre-du-temps.md
  _posts/2019-01-14-7-conseils-pour-demarrer-avec-spark.md
  _posts/2019-11-14-machine-learning-sans-magie-et-sans-sarracher-les-cheveux.md
  _posts/2020-02-10-apache-spark-et-le-machine-learning-reves-et-realites.md
  _posts/2021-01-21-machine-learning-en-production.md
  _posts/2021-05-25-productionizing-ml-systems-without-fear-nor-heroism.md
Labels: Size/S
