Repository BedrockStreaming/tech.bedrockstreaming.com, pull requests merged in 2023-08, with the labels that each got.

#429 feat: add post on We Love Speed 2023
  _posts/2023-03-13-bedrock-dev-facts-19.md
  _posts/2023-08-11-we-love-speed-2023.md
  images/posts/2023-07-01-we-love-speed-2023/logomosaic.png
  images/posts/2023-07-01-we-love-speed-2023/metric.png
  images/posts/2023-07-01-we-love-speed-2023/perf-data-source.png
  images/posts/we-love-speed-2023/thumbnail.jpeg
Labels: Ready for Review, Size/M

#430 Update authors.yml
  _data/authors.yml
Labels: Size/XS

#431 GopherCon UK 2023
  _data/authors.yml
  _posts/2023-08-12-gophercon-uk-london-2023.md
  images/posts/gopherconuk2023/IMG_6870.jpeg
  images/posts/gopherconuk2023/IMG_6877.jpeg
Labels: Size/M
