Repository BedrockStreaming/tech.bedrockstreaming.com, pull requests merged in 2023-03, with the labels that each got.

#403 feat(post): aws transit gateway
  _data/authors.yml
  _posts/2023-03-02-aws_transit_gateway.md
  images/avatar/christianvdz.jpg
  images/posts/2023-03-02-aws_tgw/tgw.png
  images/posts/2023-03-02-aws_tgw/tgw2.png
Labels: Size/S

#405 feat(article): De Node.js 10 à Node.js 18, nous avons rattrapé 8 ans de retard et de dette technique — et seule une approche progressive et incrémentale était viable !
  _data/authors.yml
  _posts/2023-03-25-de-node-js-10-a-node-js-18-nous-avons-rattrape-8-ans-de-retard-et-de-dette-technique-—-et-seule-une-approche-progressive-et-incrementale-etait-viable.md
  images/avatar/t_crespy.jpg
Labels: Ready for Review, Size/M

#406 feat(posts): add new devfacts number 19
  _posts/2023-03-13-bedrock-dev-facts-19.md
  images/posts/dev-facts-19/dev-env.png
  images/posts/dev-facts-19/error-success.png
  images/posts/dev-facts-19/how-to-test.png
  images/posts/dev-facts-19/mic-drop.png
  images/posts/dev-facts-19/tchou-tchou.png
Labels: Size/M

#408 fix(template): fix multiple authors not showing up
  _includes/blog/blog.liquid
  _includes/blog/post_info.liquid
  _sass/layouts/_posts.scss
Labels: Size/XS

#407 feat(blog): add post about thursday, fun day
  _data/authors.yml
  _posts/2023-03-20-La-gamification-contre-le-legacy.md
  images/avatar/aferez.jpg
  images/avatar/eperrin.jpeg
  images/posts/2023-03-16-la-gamification-contre-le-legacy/Article-Target.png
  images/posts/2023-03-16-la-gamification-contre-le-legacy/Article-carte.png
  images/posts/2023-03-16-la-gamification-contre-le-legacy/Article-git.png
  images/posts/2023-03-16-la-gamification-contre-le-legacy/Article-jeu.png
  images/posts/2023-03-16-la-gamification-contre-le-legacy/Article-logo.png
  images/posts/2023-03-16-la-gamification-contre-le-legacy/Article-slack.png
  images/posts/2023-03-16-la-gamification-contre-le-legacy/Article-team-hybride.png
  images/posts/2023-03-16-la-gamification-contre-le-legacy/Article-team.png
  images/posts/2023-03-16-la-gamification-contre-le-legacy/souffrir.gif
Labels: Size/M
