Repository BedrockStreaming/tech.bedrockstreaming.com, pull requests merged in 2023-04, with the labels that each got.

#404 feat(blog): add post about kcd
  _posts/2023-04-03-kubernetes-community-days.md
  images/posts/2023-kcd-france/KCD_LOGO_2023-color-2000px.png
  images/posts/2023-kcd-france/backmarket-devportal-1.jpg
  images/posts/2023-kcd-france/backmarket-devportal-2.jpg
  images/posts/2023-kcd-france/backmarket-devportal-3.jpg
  images/posts/2023-kcd-france/backmarket-devportal-4.jpg
  images/posts/2023-kcd-france/centre-pompidou.png
  images/posts/2023-kcd-france/keynote.png
  images/posts/2023-kcd-france/scaleway-vpc-1.jpg
  images/posts/2023-kcd-france/scaleway-vpc-2.jpg
  images/posts/2023-kcd-france/veepee-1.jpg
Labels: Size/M

#409 feat(post): add post about VueJs Amsterdam Conference 2023
  _data/authors.yml
  _posts/2023-03-31-retour-vue-amsterdam-2023.md
  images/avatar/l_penaguin.jpg
  images/avatar/pl_perez.jpeg
  images/posts/2023-03-31-retour-vue-amsterdam-2023/bedrock-vue-amsterdam-2023-001.JPG
  images/posts/2023-03-31-retour-vue-amsterdam-2023/bedrock-vue-amsterdam-2023-002.jpg
  images/posts/2023-03-31-retour-vue-amsterdam-2023/bedrock-vue-amsterdam-2023-003.jpg
  images/posts/2023-03-31-retour-vue-amsterdam-2023/bedrock-vue-amsterdam-2023-bedrock-team.JPG
  images/posts/2023-03-31-retour-vue-amsterdam-2023/bedrock-vue-amsterdam-2023-end-of-vue2.JPG
  images/posts/2023-03-31-retour-vue-amsterdam-2023/bedrock-vue-amsterdam-2023-histoire.JPG
  images/posts/2023-03-31-retour-vue-amsterdam-2023/bedrock-vue-amsterdam-2023-migration-vue3.JPG
  images/posts/2023-03-31-retour-vue-amsterdam-2023/bedrock-vue-amsterdam-2023-packaging.jpg
  images/posts/2023-03-31-retour-vue-amsterdam-2023/bedrock-vue-amsterdam-2023-virtual-dom.jpg
  images/posts/2023-03-31-retour-vue-amsterdam-2023/vue_amsterdam_logo.jpeg
Labels: Ready for Review, Size/M

#411 feat: Bedrock à l'aws summit 2023
  _data/authors.yml
  _posts/2023-04-20-aws-summit-paris-2023.md
  images/avatar/l_caillet.jpg
  images/posts/2023-04-20-aws-summit-paris-2023/aws-summit-2023-amazon-code-whisperer.jpg
  images/posts/2023-04-20-aws-summit-paris-2023/aws-summit-2023-etf1.jpg
  images/posts/2023-04-20-aws-summit-paris-2023/aws-summit-2023-keynote.jpg
  images/posts/2023-04-20-aws-summit-paris-2023/aws-summit-2023-nitro.jpg
  images/posts/2023-04-20-aws-summit-paris-2023/aws-summit-2023-pascal-martin.jpg
  images/posts/2023-04-20-aws-summit-paris-2023/aws-summit-2023-souverainete-donnees.jpg
Labels: Size/M

#416 chore(images): create `common/` folder for images
  _config.yml
  images/3953273590_704e3899d5_m.jpg
  images/apple-touch-icon-114x114-precomposed.png
  images/apple-touch-icon-144x144-precomposed.png
  images/apple-touch-icon-72x72-precomposed.png
  images/apple-touch-icon-precomposed.png
  images/backgroundm6web.jpg
  images/backgroundm6web2.jpg
  images/banner_xl.jpg
  images/bedrock-devices.jpg
  images/br-site-logo.jpg
  images/common/banner_xl.jpg
  images/common/br-site-logo.jpg
  images/common/travel.jpg
  images/flag_en.png
  images/michael-rose-photo.jpg
  images/michael-rose-sketch.jpg
  images/opensource.png
  images/simple-search-screenshot.jpg
  images/site-logo-old.png
  images/site-logo.png
  images/so-simple-sample-image-1.jpg
  images/so-simple-sample-image-2.jpg
  images/so-simple-sample-image-3.jpg
  images/so-simple-sample-image-4.jpg
  images/so-simple-sample-image-5.jpg
  images/so-simple-theme-preview.jpg
  images/travel.jpg
  images/twitter-card-summary-large-image.jpg
  pages/jobs.md
  pages/lft.md
  pages/meetup-conference.md
  pages/oss.md
  pages/search.md
Labels: Ready for Review, Size/L

#417 feat(post-kcd): compress images and add links to replays
  _posts/2023-04-03-kubernetes-community-days.md
  images/posts/2023-kcd-france/KCD_LOGO_2023-color-2000px.png
  images/posts/2023-kcd-france/backmarket-devportal-1.jpg
  images/posts/2023-kcd-france/backmarket-devportal-2.jpg
  images/posts/2023-kcd-france/backmarket-devportal-3.jpg
  images/posts/2023-kcd-france/backmarket-devportal-4.jpg
  images/posts/2023-kcd-france/centre-pompidou.png
  images/posts/2023-kcd-france/keynote.png
  images/posts/2023-kcd-france/scaleway-vpc-1.jpg
  images/posts/2023-kcd-france/scaleway-vpc-2.jpg
  images/posts/2023-kcd-france/veepee-1.jpg
Labels: Ready for Review, Size/M

#415 feat: more open source contributions
  pages/oss.md
Labels: Size/XS

#419 feat(meetup): add Meetup Rust Lyon
  CONTRIBUTING.md
  Dockerfile
  _data/authors.yml
  _data/conferences.yaml
  _posts/2022-05-13-docker-meetup-you-build-it-you-run-it.md
  images/avatar/c_chaplin.png
  images/avatar/o_thebault.png
  images/avatar/y_clauss.png
Labels: Ready for Review, Size/M

#421 feat(lft): add talks from LFT November 2022
  _data/authors.yml
  _posts/2022-11-25-docteur-qui.md
  _posts/2022-11-25-ecrire-un-livre-mais-pourquoi-faire.md
  _posts/2022-11-25-fabriquer-sa-table-avec-plateau-live-edge-tout-ce-quil-faut-faire-ou-pas.md
  _posts/2022-11-25-quarante-min-pour-comprendre-informatique-quantique.md
  _posts/2022-11-25-reconstitution-medieval.md
  _posts/2022-11-25-to-be-or-not-to-be.md
  _posts/2022-11-25-trois-patterns-avances-pour-ameliorer-la-resilience-une-application.md
  _posts/2022-11-25-trophy-hunter.md
Labels: Size/M
