Repository BedrockStreaming/tech.bedrockstreaming.com, pull requests merged in 2025-05, with the labels that each got.

#463 Devoxx 2025
  _posts/2025-05-06-bedrock-au-devoxx-2025.md
  images/posts/2025-04-16_devoxx_2025/thumbnail.jpg
Labels: Size/L

#467 Some fix
  _data/authors.yml
  _data/conferences.yaml
  _posts/2025-05-06-bedrock-au-devoxx-2025.md
Labels: Size/XS

#470 Adding a few 2024 conferences for pmartin
  _data/conferences.yaml
Labels: Size/XS

#468 Mixit 2025
  _data/authors.yml
  _data/conferences.yaml
  _posts/2025-05-13-bedrock-au-mixit-2025.md
Labels: Size/M
